name: npm-publish
on:
  push:
    branches:
      - main
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Copy & Package for npm publish
        run: cp package.json dist/ && ls -l dist

      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          workspace: "./dist"
          commit_pattern: "[\\s\\S]*Release (\\S+)"
          publish_command: "yarn"
          publish_args: " --access public"
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
